version: "3.9"
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - RESTORE_DELAY_MINUTES=${RESTORE_DELAY_MINUTES:-5}
      - DATA_DIR=/app/data
      - TZ=Europe/Rome
    volumes:
      - rolebot_data:/app/data
volumes:
  rolebot_data:
    driver: local
